[package]
name = "dns-encoding"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
trust-dns-proto = "0.19.5"
base32 = "0.4.0"